PUT http://localhost:5279/auth/passwordreset
Content-Type: application/json
X-Audience: http://localhost:5279
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzIiwibmJmIjoxNzAzODI1MDI3LCJleHAiOjE3MDM5MTE0MjcsImlhdCI6MTcwMzgyNTAyNywiaXNzIjoiYnJld2xvZ3MtYXBpIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIn0.h3lpHltTQWGXXF1Qk1739k4wmNza_j5fWlyyMKHnuLeV9Y2DUoJdGZi1uNmKa3AxkZL9aPRZHKG84wdqf5JUgg

{
  "email": "rogelinmitre@gmail.com",
  "password": "Ilovebaab123!"
}
