PUT http://localhost:5279/auth/passwordreset
Content-Type: application/json
X-Audience: http://localhost:5279
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzIiwibmJmIjoxNzAzOTE0OTE1LCJleHAiOjE3MDQwMDEzMTUsImlhdCI6MTcwMzkxNDkxNSwiaXNzIjoiYnJld2xvZ3MtYXBpIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIn0.n5UXSPIxn1miHx9eQ32Fg6C-IF4PkCTuW9y2H5SSayVbkbGQqRtK_83uVTc7y6VUovjHT_ZpdRDvVXPm_2sq5g

{
  "email": "alymitre@gmail.com",
  "newPassword": "Deperu97!"
}
