POST http://localhost:5279/register
Content-Type: application/json

{
  "firstName": "Alyssa",
  "lastName": "Mercado",
  "email": "alymitre@gmail.com",
  "password": "Ilovebaab1!",
  "passwordConfirm": "Ilovebaab1!"
}
