// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using brewlogsMinimalApi.Data;

#nullable disable

namespace brewlogsMinimalApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231101042605_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("brewlogsMinimalApi.Model.Brewlog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrewRatio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrewerUsed")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoffeeName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.Property<int>("Dose")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Grind")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.Property<string>("Roast")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Brewlogs");
                });
#pragma warning restore 612, 618
        }
    }
}
